name: Java CI with Gradle
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ArmorStandEditor Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build shaded JAR
        run: ./gradlew clean shadowJar --no-daemon

      - name: Get Version
        id: get_version
        run: echo "version=$(ls build/libs/ArmorStandEditor-*-all.jar | sed 's/.*ArmorStandEditor-\(.*\)-all.jar/\1/')" >> $GITHUB_OUTPUT

      - name: Upload built JAR
        uses: actions/upload-artifact@v7
        with:
          name: ArmorStandEditor-${{ steps.get_version.outputs.version }}
          path: build/libs/ArmorStandEditor-*-all.jar
          if-no-files-found: error
